import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Navigation from "./_components/Navigation";

interface Props {
  children: React.ReactNode;
}

const Inter = localFont({
  src: "../public/fonts/Inter-Regular.woff2",
});

function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={Inter.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
export default RootLayout;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
